#!/usr/bin/env python3
"""Encrypt secrets.json into secrets.enc.js for the passphrase lock (js/unlock.js).

secrets.json is gitignored and holds the values that must not be public:
  {"SHEET_ID": "...", "SHEETS_API_KEY": "", "FIREBASE": null, "TRIP_DOC_ID": "..."}

Usage: python3 tools/seal.py [--site https://you.github.io/japan-trip/]
Needs the `cryptography` package (pip install cryptography).
"""
import argparse, base64, getpass, json, os, sys
from pathlib import Path
from urllib.parse import quote

from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.ciphers.aead import AESGCM
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC

ROOT = Path(__file__).resolve().parent.parent
ITERATIONS = 600_000
b64 = lambda b: base64.b64encode(b).decode()

ap = argparse.ArgumentParser()
ap.add_argument('--site', help='hosted URL, to print a one-tap setup link')
args = ap.parse_args()

secrets = json.loads((ROOT / 'secrets.json').read_text())
passphrase = getpass.getpass('Passphrase: ').strip()
if len(passphrase) < 12:
    sys.exit('Use at least 12 characters — a few random words is ideal.')
if getpass.getpass('Again: ').strip() != passphrase:
    sys.exit("Passphrases don't match.")

salt, iv = os.urandom(16), os.urandom(12)
key = PBKDF2HMAC(hashes.SHA256(), 32, salt, ITERATIONS).derive(passphrase.encode())
data = AESGCM(key).encrypt(iv, json.dumps(secrets).encode(), None)

sealed = {'iterations': ITERATIONS, 'salt': b64(salt), 'iv': b64(iv), 'data': b64(data)}
(ROOT / 'secrets.enc.js').write_text(
    '// Generated by tools/seal.py. Encrypted; safe to commit.\n'
    f'export const SEALED = {json.dumps(sealed, indent=2)};\n')
print('Wrote secrets.enc.js')
if args.site:
    print('Setup link (send privately):', args.site.rstrip('/') + '/#key=' + quote(passphrase))
